#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

docker pull quay.io/goswagger/swagger
alias swagger="docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"

swagger generate server -t swgate -f ./grpc.swagger.json --exclude-main -A slbukswgate