#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

protoc --proto_path=grpc \
    --go_out=grpc --go_opt=paths=source_relative \
    --go-grpc_out=grpc --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=grpc --grpc-gateway_opt=logtostderr=true  --grpc-gateway_opt=paths=source_relative \
    --openapiv2_out=. --openapiv2_opt=logtostderr=true \
    grpc/grpc.proto