// Code generated by go-swagger; DO NOT EDIT.

package slb_uk_entities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewSlbUkEntitiesGetEntitiesParams creates a new SlbUkEntitiesGetEntitiesParams object
//
// There are no default values defined in the spec.
func NewSlbUkEntitiesGetEntitiesParams() SlbUkEntitiesGetEntitiesParams {

	return SlbUkEntitiesGetEntitiesParams{}
}

// SlbUkEntitiesGetEntitiesParams contains all the bound params for the slb uk entities get entities operation
// typically these are obtained from a http.Request
//
// swagger:parameters SlbUkEntities_GetEntities
type SlbUkEntitiesGetEntitiesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSlbUkEntitiesGetEntitiesParams() beforehand.
func (o *SlbUkEntitiesGetEntitiesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
