// Code generated by go-swagger; DO NOT EDIT.

package slb_uk_entities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mgalagan/slbuk/swgate/models"
)

// SlbUkEntitiesGetEntitiesOKCode is the HTTP code returned for type SlbUkEntitiesGetEntitiesOK
const SlbUkEntitiesGetEntitiesOKCode int = 200

/*SlbUkEntitiesGetEntitiesOK A successful response.

swagger:response slbUkEntitiesGetEntitiesOK
*/
type SlbUkEntitiesGetEntitiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.GrpcGetEntityResponse `json:"body,omitempty"`
}

// NewSlbUkEntitiesGetEntitiesOK creates SlbUkEntitiesGetEntitiesOK with default headers values
func NewSlbUkEntitiesGetEntitiesOK() *SlbUkEntitiesGetEntitiesOK {

	return &SlbUkEntitiesGetEntitiesOK{}
}

// WithPayload adds the payload to the slb uk entities get entities o k response
func (o *SlbUkEntitiesGetEntitiesOK) WithPayload(payload *models.GrpcGetEntityResponse) *SlbUkEntitiesGetEntitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the slb uk entities get entities o k response
func (o *SlbUkEntitiesGetEntitiesOK) SetPayload(payload *models.GrpcGetEntityResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SlbUkEntitiesGetEntitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SlbUkEntitiesGetEntitiesDefault An unexpected error response.

swagger:response slbUkEntitiesGetEntitiesDefault
*/
type SlbUkEntitiesGetEntitiesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RPCStatus `json:"body,omitempty"`
}

// NewSlbUkEntitiesGetEntitiesDefault creates SlbUkEntitiesGetEntitiesDefault with default headers values
func NewSlbUkEntitiesGetEntitiesDefault(code int) *SlbUkEntitiesGetEntitiesDefault {
	if code <= 0 {
		code = 500
	}

	return &SlbUkEntitiesGetEntitiesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the slb uk entities get entities default response
func (o *SlbUkEntitiesGetEntitiesDefault) WithStatusCode(code int) *SlbUkEntitiesGetEntitiesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the slb uk entities get entities default response
func (o *SlbUkEntitiesGetEntitiesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the slb uk entities get entities default response
func (o *SlbUkEntitiesGetEntitiesDefault) WithPayload(payload *models.RPCStatus) *SlbUkEntitiesGetEntitiesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the slb uk entities get entities default response
func (o *SlbUkEntitiesGetEntitiesDefault) SetPayload(payload *models.RPCStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SlbUkEntitiesGetEntitiesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
